### ISSUE TITLE
Activation Issue

### ISSUE THREAD

**Issue by majidcreativedev** [lautr/strapi-plugin-duplicate-button#1]
I have installed the plugin but there is no place or option to activate it. Please help, Thank you.

**Comment by lautr** [comment]
it automatically activates after enabling it in the config:

Add the following attribute in the `config/plugins.js` file:
```
'duplicate-button': true
```
Or if you do not have the plugins.js file yet, add the file with the following contents:
```
module.exports = () => ({
  'duplicate-button': true,
});
```

If that doesn't work please create a repo to reproduce the issue and i will take a look.

**Comment by lautr** [comment]
@majidcreativedev I'll be closing this issue, feel free to open a new one with an example if activating the plugin does not work.
