### ISSUE TITLE
Incompatible versions of the plugin

### ISSUE THREAD

**Issue by pashaproton** [lautr/strapi-plugin-duplicate-button#11]
The current plugin version according to the package.json file is [1.1.5](https://github.com/lautr/strapi-plugin-duplicate-button/blob/main/package.json#L3). But the version on the npmjs.com is old ([1.0.4](https://www.npmjs.com/package/strapi-plugin-duplicate-button)) which is an issue for users who are trying to install the plugin from the npmjs.com repository.

**Comment by lautr** [comment]
Hi @pashaproton , thanks for the report, version is updated, and CD is running again.
