### ISSUE TITLE
Does not check for unique value rules

### ISSUE THREAD

**Issue by jmather-aipm** [lautr/strapi-plugin-duplicate-button#14]
If an item has a field called Value that is set to be required and unique and you click the Duplicate button to go to the "...create/clone/<id>" endpoint, you are able to save the cloned item with the same value again that is supposed to be unique.

![image](https://github.com/lautr/strapi-plugin-duplicate-button/assets/39349082/bcd02168-edd0-469e-970e-705a7df1bfdf)

![image](https://github.com/lautr/strapi-plugin-duplicate-button/assets/39349082/4a90a324-e982-4032-a34d-cb5aa868e2d1)

**Comment by lautr** [comment]
Hi @jmather-aipm, thanks fot the feedback, the issue you are describing lies within strapis internal clone logic, my addon just exposes it in the edit context so it can't be solved on this level

**Comment by jmather-aipm** [comment]
Hi @lautr, okay, that makes sense.  That's good to know -- thank you for the explanation
