### ISSUE TITLE
Question: What does this plugin do differently from the native duplicate button?

### ISSUE THREAD

**Issue by boazpoolman** [lautr/strapi-plugin-duplicate-button#16]
Hi!

I was looking at this plugin and wondered if there is anything that this plugin does differently/better then the default duplicate button in Strapi admin.

![Scherm­afbeelding 2023-07-31 om 17 58 03](https://github.com/lautr/strapi-plugin-duplicate-button/assets/9551934/08bc0174-ae9f-4fa7-9dbb-b0605cb15741)

**Comment by lautr** [comment]
hi @boazpoolman

in short; no. It really only exposes the existing duplicate functionality in the edit view.

**Comment by ww7** [comment]
In my case, the plugin creates a full duplicate when Strapi button duplicate is loosing images.
