### ISSUE TITLE
Not working with versioning

### ISSUE THREAD

**Issue by wojjee** [lautr/strapi-plugin-duplicate-button#21]
HI i think this function is not working with versionning app. Every time im creating new duplicate and publishing it the orginal content record is removed.

**Comment by lautr** [comment]
Hi @wojjee , unfortunately i can only expose the existing duplicate logic from within strapi so there is no way to change how the actual duplication is handled.

**Comment by sushmavoleti** [comment]
I also have the same problem. Did you find any solution @wojjee?

**Comment by wojjee** [comment]
nope, unfortunately i did not find any solution for this.

**Comment by sushmavoleti** [comment]
I fixed it using by changing vuid in beforeCreate lifecycle hook.
    if (pageURL.includes("clone")) {
      const vuid: string = generateVUID();
      event.params.data.versionNumber = 1;
      if (event?.model?.columnToAttribute?.vuid) event.params.data.vuid = vuid;
    }
