### ISSUE TITLE
Plugin incompatible with Strapi v4.15.2+

### ISSUE THREAD

**Issue by Kapcash** [lautr/strapi-plugin-duplicate-button#22]
Hi!

I think the plugin is not compatible with the Strapi version v4.15.2+.
Apparently, it imports a module from Strapi source code that is not documented and it changed in this version of Strapi, resulting in an error at build:

> ⠧ Building admin panel `[ERROR] Module not found: Error: Package path ./admin/src/content-manager/hooks/usePluginsQueryParams is not exported from package my-project/node_modules/@strapi/admin`

Removing the plugin fixes the build command.

See https://github.com/strapi/strapi/issues/18711

**Comment by PenguinOfWar** [comment]
This was fixed in #19. Try updating the plugin to `1.1.14`.

**Comment by lautr** [comment]
thanks to @PenguinOfWar this should be fixed with the most current release.
