### ISSUE TITLE
Strapi 4: Different behaviour than Strapi's duplicate button

### ISSUE THREAD

**Issue by paulwellnerbou** [lautr/strapi-plugin-duplicate-button#26]
In Strapi 4, the behaviour of this button is different than the behaviour of Strapi's duplicate button in the list:

* The default Strapi calls the `auto-clone` endpoint and saves the the duplicated entity and shows the already saved data.
* This button opens the cloned data (without saving) and calls the `clone` endpoint afterwards

While I personally prefer the second approach in principle, I would still like to do both methods the exakt same things.

In addition to that, the Strapi duplicate feature (Strapi 4.2.24) is not removing the backreferences of localized entities. I implemented a workaround for this, with works fine in our case, but it only works for the default Strapi behaviour.

**Comment by lautr** [comment]
Thanks!
