### ISSUE TITLE
Error: "AxiosError is not defined"

### ISSUE THREAD

**Issue by mimartinez** [lautr/strapi-plugin-duplicate-button#28]
Hi,

Upgrading to version 1.2.14 stopped working because an error occurred: `AxiosError is not defined`

![Captura de pantalla 2024-06-04 a las 13 11 43](https://github.com/lautr/strapi-plugin-duplicate-button/assets/888965/ef8467d1-68fc-45b0-b032-92a12990a392)

**Comment by lautr** [comment]
Hi @mimartinez 

can you check iv 1.2.15 fixes the issue for you?

Thanks

**Comment by mimartinez** [comment]
Hi @lautr 

The error has disappeared but now it is another one because it seems that you have to import something because it does not find a function.

The error is now:

`ReferenceError: setClonedEntryId is not defined`

![Captura de pantalla 2024-06-11 a las 13 43 01](https://github.com/lautr/strapi-plugin-duplicate-button/assets/888965/530a1c34-832f-43ae-a4e5-5ec346249238)

Thanks

**Comment by lautr** [comment]
It seems this is due to a badly handled error from Strapi internal copy logic, i reverted some changes that may help avoid the issue, but there are scenarios in which Strapi copy logic just does not work.
