### ISSUE TITLE
Does not duplicate translations

### ISSUE THREAD

**Issue by fabianmu** [lautr/strapi-plugin-duplicate-button#5]
See title ;)
I'd be great if this plugin would also clone the translations of an item (of course also in draft mode)

**Comment by lautr** [comment]
hi @fabianmu unfortunately that is an issue with strapi itself - see https://github.com/strapi/strapi/issues/13584 and can't be adressed in this plugin as it uses strapis internal duplicate logic

**Comment by fabianmu** [comment]
A bummer, thanks @lautr!
