### ISSUE TITLE
Feature Request: Slugify plugin causes problems when duplicating a collection

### ISSUE THREAD

**Issue by oDinZu** [lautr/strapi-plugin-duplicate-button#7]
The slugify plugin allows for auto generated pretty titles for each collection. 

This auto generated pretty url bugs out when duplicating a collection.

**Comment by lautr** [comment]
@csharpee does the same problem occur when you are using the duplicate function from the list view? If so the issue lies with strapis underlying duplicate logic, which is simply exposed through this plugin.

**Comment by oDinZu** [comment]
@lautr yeah, on the list view and while duplicating within the collection type itself.

**Comment by oDinZu** [comment]
The slugify plugin auto updates after change of specified *field*, but it produces an error when using the duplicate button.

**Comment by oDinZu** [comment]
I added the **slugifyWithCount** option to see if it would at least create a new slug if has the same slug, but that resulted in the same error as shown above.

**Comment by lautr** [comment]
@csharpee thanks for the information - unfortunately that seems to be an issue with strapis internal duplicate logic and would have to be fixed on that end, this plugin simply exposes the existing duplicate logic within the edit view

**Comment by oDinZu** [comment]
Unfortunately, this is an unofficial Strapi plugin, I hope this gets updated. I know there are bulk edits in the works, but unsure if it revolves around duplication of collection types.

I tried disabling the plugin for the time being, but this didn't even work.
