### ISSUE TITLE
Update Node Version to support 18.x.x

### ISSUE THREAD

**Issue by kuyazee** [lautr/strapi-plugin-duplicate-button#8]
First of all, thank you for making this plugin! 

Next, I would make a PR but I'm not adept at Node.JS versioning and Node.JS in general, it would be great if you could release a versoin that supports node **18.7.0**

```
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error strapi-plugin-duplicate-button@1.0.4: The engine "node" is incompatible with this module. Expected version ">=12.x.x <=16.x.x". Got "18.7.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by lautr** [comment]
hi @kuyazee , you are welcome, i released a new version that supports node 18

**Comment by kuyazee** [comment]
Good Day @lautr, I'm not quite sure but it seems that the package still can't be installed with 18.x.x.

I'm still getting the same issue when running this command `yarn add strapi-plugin-duplicate-button`

I've also run `yarn cache clean` but the error is still the same for some reason

**Comment by lautr** [comment]
@kuyazee there was an issue with NPM not publishing new versions, it resolved now and the newest version should work with node 18

**Comment by kuyazee** [comment]
Thanks a bunch @lautr !
